import { useRouter } from "next/router";
import { useGlobalContext } from "@/context/MyContext";
import { useCallback } from "react";



//This is a coustum hook. which will return the function. When the function is called it open a leadModel.

export default function useLeadModel() {


    const router = useRouter();         //To grab the url 
    const { setLeadFormData, setIsLeadsModelOpen } = useGlobalContext();            //state to open and close the lead model


    //using callback to optimise the return function. When any state change in component the openLoeadModel does not redefine.
    const openLeadModel = useCallback(

       
        (event, v_slug, v_id,by="form") => {             //we lead is generated by model in by="form", and for call we pass call.
            const leadData = {
                url: router.asPath,
                venue_id: v_id,
                venue_slug: v_slug,
                type: "click",
                request_handle_by: by
            };

            // console.log(leadData)

            setLeadFormData(leadData);              //Set the data in the global state so that we can pass this data to the api.
            setIsLeadsModelOpen(true);              //After setting the , opening the lead model     
           
        },
        [router.asPath, setLeadFormData, setIsLeadsModelOpen]           //onChange of router.asPath openLeadModel function redefine
    );

    return { openLeadModel };           
}

